services:
  backend:
    build: .
    container_name: emerald-be
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: emerald_db
    command: node dist/main.js 
  postgres:
    image: postgres:16-alpine
    container_name: emerald-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: emerald_db
    ports:
      - "5432:5432"
    volumes:
      - emerald_postgres_data:/var/lib/postgresql/data

volumes:
  emerald_postgres_data: